"""initial schema: users + moods

Revision ID: 9ec12d13dd4b
Revises: 6ed1e1c6f02c
Create Date: 2025-08-09 15:42:12.387295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec12d13dd4b'
down_revision: Union[str, Sequence[str], None] = '6ed1e1c6f02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
